const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('catAPI', {
  onCursor: (cb) => ipcRenderer.on('cursor', (_e, pos) => cb(pos)),
  onKey: (cb) => ipcRenderer.on('key', () => cb()),
  chatSend: (payload) => ipcRenderer.send('chat-send', payload),
  onChatChunk: (cb) => ipcRenderer.on('chat-chunk', (_e, d) => cb(d)),
  getProfile: () => ipcRenderer.invoke('profile:get'),
  saveProfile: (p) => ipcRenderer.send('profile:save', p),
  showMenu: () => ipcRenderer.send('show-menu'),
  onNotify: (cb) => ipcRenderer.on('notify', (_e, text) => cb(text)),
  onMoodPrompt: (cb) => ipcRenderer.on('mood-prompt', (_e, payload) => cb(payload)),
  onWeeklySummary: (cb) => ipcRenderer.on('weekly-summary', (_e, text) => cb(text)),
  recordMood: (payload) => ipcRenderer.send('mood:response', payload),
  onPomoActive: (cb) => ipcRenderer.on('pomo-active', (_e, v) => cb(v)),
  addReminder: (r) => ipcRenderer.send('reminder:add', r),
  createTask: (t) => ipcRenderer.send('task:create', t),
  onLayout: (cb) => ipcRenderer.on('layout', (_e, l) => cb(l)),
  dragStart: () => ipcRenderer.send('drag-start'),
  dragMove: () => ipcRenderer.send('drag-move'),
  dragEnd: () => ipcRenderer.send('drag-end'),
  resize: (dir) => ipcRenderer.send('resize', dir),
  setIgnore: (v) => ipcRenderer.send('set-ignore', v),
  quit: () => ipcRenderer.send('quit'),
});
